services: 
  postgresql:
    container_name: odoo19_postgresql
    image: postgres:17
    restart: always
    networks:
      - postgres-network
    env_file:
      - ./.env
    volumes: 
      - postgresql-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
volumes: 
  postgresql-data:
networks:
  postgres-network:
    external: true
